name: Windows x64
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -A x64
      - name: Build
        run: cmake --build build --config Release --parallel
